POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlaW1hbCIsImlkIjoiNjQxYzRmOWM1ZWQ3NjhhN2JkY2UzY2Q1IiwiaWF0IjoxNjc5NTgwNjAxfQ.V0mpTkb1uX-8hNbicFSQ5mwviSpW1AXEBXni0aTLCas

{
    "title": "Elämäni kiven sisällä",
    "author": "Mölli Rosvonen",
    "url": "google.com/dontdocrimes",
    "likes": 2
}